website/case/urls.py
from django.urls import path
from .views import (
    ContatoCreateView,
    ContatoDeleteView,
    ContatoDetailView,
    ContatoListView,
    ContatoUpdateView,
)
app_name = 'contato'
urlpatterns = [
    path('', ContatoListView.as_view(), name='contato-list'),
    path('create/', ContatoCreateView.as_view(), name='contato-create'),
    path('<int:pk>/', ContatoDetailView.as_view(), name='contato-detail'),
    path('<int:pk>/update/', ContatoUpdateView.as_view(), name='contato-update'),
    path('<int:pk>/delete/', ContatoDeleteView.as_view(), name='contato-delete'),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('case.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/case/models.py
from django.db import models
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField

class Contato(models.Model):
    nome = models.CharField(max_length = 120, verbose_name='Nome')
    celular = PhoneNumberField(verbose_name='Celular')
    cargo = models.CharField(max_length = 120, verbose_name='Cargo', blank='True')
    empresa = models.CharField(max_length = 50, verbose_name='Empresa', blank='True')
    email = models.EmailField(max_length = 120, verbose_name='Email', blank='True')

    def get_absolute_url(self):
        return reverse("contato:contato-detail", kwargs={"pk": self.id})

website/case/forms.py
from django import forms
from .models import Contato

class ContatoModelForm(forms.ModelForm):
    nome = forms.CharField(widget=forms.TextInput(
            attrs={'placeholder': 'Nome do contato'}))

    celular = forms.CharField(help_text='Incluindo código do pais, exemplo +55011',  widget=forms.TextInput(
            attrs={'placeholder': 'Número do celular'}))

    
    class Meta:
        model = Contato
        fields =['nome','celular','cargo','empresa','email',]

    def clean(self):
        cleaned_data = super(ContatoModelForm, self).clean()
        nome = cleaned_data.get('nome')
        email = cleaned_data.get('email')
        celular = cleaned_data.get('celular')
        if not nome and not email:
            raise forms.ValidationError('Ops preencha os campos obrigatórios!')

website/case/views.py
from django.urls import reverse
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    ListView,
    DeleteView
)

from .forms import ContatoModelForm
from .models import Contato
class ContatoCreateView(CreateView):
    template_name = 'contato/contato_create.html'
    form_class = ContatoModelForm
    model = Contato

class ContatoListView(ListView):
    template_name = 'contato/contato_list.html'
    model = Contato

class ContatoDetailView(DetailView):
    template_name = 'contato/contato_detail.html'
    model = Contato

class ContatoUpdateView(UpdateView):
    template_name = 'contato/contato_create.html'
    form_class = ContatoModelForm
    model = Contato

class ContatoDeleteView(DeleteView):
    template_name = 'contato/contato_delete.html'
    model = Contato
    def get_success_url(self):
        return reverse('contato:contato-list')

website/case/templates/contato/contato_create.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<style>
.form-row{
  margin: 30px;
}
.mdl-button{
  margin: 30px;
}
.mdl-card__title-text{
  margin-left: 20px;
}
</style>
<form method="post" novalidate>
  {% csrf_token %}

  <div class="mdl-card__title">
      <h2 class="mdl-card__title-text">Cadastro</h2>

  </div>
  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
  {% endfor %}

  {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
  {% endif %}
<div class="form-row">
  {% for field in form.visible_fields %}
    <div class="form-group col-md-6">
      {{ field.label_tag }}

      {% if form.is_bound %}
        {% if field.errors %}
          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
        {% render_field field class="form-control" %}
      {% endif %}

      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}
</div>
<button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">Salvar</button>

</form>

{% endblock %}

website/case/templates/contato/contato_delete.html
{% load staticfiles %}
<dialog class="mdl-dialog">
    <h6>Deseja excluir {{ object.nome }}?</h6>
    <div class="mdl-dialog__actions">
        <input id="demo-show-snackbar" type="submit" class="mdl-button mdl-js-button mdl-button--accent" value="Excluir">
        <button type="button" class="mdl-button close">Cancelar</button>
    </div>
</dialog>
<div id="demo-snackbar-example" class="mdl-js-snackbar mdl-snackbar">
  <div class="mdl-snackbar__text"></div>
  <button class="mdl-snackbar__action" type="button"></button>
</div>
<script type="text/javascript" src="{% static 'js/snackbar.js' %}"></script>

website/case/templates/contato/contato_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<style>
    #fab {
    position: fixed;
    display: block;
    right: 0;
    bottom: 0;
    margin-right: 40px;
    margin-bottom: 40px;
    z-index: 900;
  }

 .demo-list-icon {
    margin-left: 30px;
  }
 .mdl-card__title{
   margin-left: 30px;
 }
 .mdl-button{
   margin-right: 10px;
   margin-top: 10px;
 }

</style>


<div class="mdl-card__title">
    <h2 class="mdl-card__title-text">{{ object.nome }}</h2>
</div>
<div class="mdl-layout-spacer"></div>
<a id="show-dialog"  class="mdl-button mdl-js-button mdl-button--icon">
  <i class="material-icons">delete</i>
</a>

{% include "contato/contato_delete.html" %}

<script type="text/javascript" src="{% static 'js/dialog.js' %}"></script>

<div class="mdl-card__actions mdl-card--border">
    <ul class="demo-list-icon mdl-list">

        <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content">
    <i class="material-icons mdl-list__item-icon">call</i>
    {{ object.email }}
  </span>
        </li>

        <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content">
    <i class="material-icons mdl-list__item-icon">email</i>
    {{ object.celular }}
  </span>
        </li>
        <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content">
    <i class="material-icons mdl-list__item-icon">business</i>
    {{ object.cargo }} na {{ object.empresa}}
  </span>
        </li>
    </ul>

</div>

<a href="{% url 'contato:contato-update' object.id %}" id="fab" class="mdl-button mdl-js-button mdl-button--fab mdl-button--primary">
     <i class="material-icons">create</i>
    </a>

{% endblock %}

website/case/templates/contato/contato_list.html
{% extends "base.html" %}
{% block content %}
<style>
  .demo-list-three {
    width: 800px;
    margin-left: 30px;
  }
  #fab {
    position: fixed;
    display: block;
    right: 0;
    bottom: 0;
    margin-right: 40px;
    margin-bottom: 40px;
    z-index: 900;
  }
</style>

<form method='GET' action=''>
</form>
{% for obj in object_list %}
<ul class="demo-list-three mdl-list">
  <li class="mdl-list__item mdl-list__item--three-line">
    <span class="mdl-list__item-primary-content">
        <i class="material-icons mdl-list__item-avatar">person</i>
        <a href='{{ obj.get_absolute_url }}'><span>{{ obj.nome }}</span></a>
    <span class="mdl-list__item-text-body">
          {{ obj.celular }} <br>
          {{ obj.email }}
        </span>
    </span>

    <a href="{{ obj.get_absolute_url }}" class="mdl-button mdl-js-button mdl-button--primary">
  DETALHES
</a>
  </li>
</ul>
{% endfor %}

<a href="{% url 'contato:contato-create' %}" id="fab" class="mdl-button mdl-js-button mdl-button--fab mdl-button--primary">
     <i class="material-icons">person_add</i>
    </a>


{% endblock content %}

website/templates/base.html
{% load static %}
<!doctype html>
<html>

<head>
  <meta charset="utf-8">

  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
  <title>Paginas de Teste</title>
  <!-- Tela principal Android e Chrome -->
  <meta name="mobile-web-app-capable" content="yes">
  <!-- Tela principal IOS e Safari-->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="Material Design Lite">

  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-deep_purple.min.css">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">


</head>

<body>

  <div class="demo-layout mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
    <header class="demo-header mdl-layout__header mdl-color--grey-900 mdl-color-text--white">
      <div class="mdl-layout__header-row">
        <span class="mdl-layout-title">Contatos</span>
    </header>

    <div class="demo-drawer mdl-layout__drawer mdl-color--grey-900 mdl-color-text--white">

      <nav class="demo-navigation mdl-navigation mdl-color--grey-900">
        <a class="mdl-navigation__link mdl-color-text--white" href="{% url 'contato:contato-list' %}"><i class="mdl-color-text--white material-icons" role="presentation">account_box</i>Contatos</a>
        <div class="mdl-layout-spacer">
        </div>
<a href="https://github.com/Phomint/EngTest#caso-de-uso" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">Caso de uso</a>
        <ul class="mdl-mini-footer__link-list">

    <li><a href="https://github.com/Phomint">By Patrick Amaral</a></li>
    <li><a href="https://github.com/Phomint/EngTest/blob/master/LICENSE">License</a></li>

  </ul>
        </nav>
    </div>
    <main class="mdl-layout__content mdl-color--grey-100">
      <div class="mdl-grid demo-content">
        <div class="demo-charts mdl-color--white mdl-shadow--2dp mdl-cell mdl-cell--12-col mdl-grid">
          {% block content %}

          {% endblock %}
        </div>

      </div>
    </main>
  </div>

  <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
</body>

</html>